## Testing
name: "Docker Base Image Commit, Build and Deployment (Deploy Target: models) (Integration Target: models)"

on: ["push"]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: temp
        run: echo "hello world"
        
