name: framework
on:
  push:
    paths:
      - ".github/workflows/base.yml"
      - ".github/workflows/framework.yml"
  workflow_run:
    workflows: [Alchemy Docker Framework Image Commit Build and Deployment]
    types:
      - completed
    
jobs:
  framework:
    strategy:
      matrix:
        branchname: ["staging", "main"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set this
        id: setthis
        run: |
          echo "naem=base.yml" >> $GITHUB_OUTPUT

      - name: check filepath change
        uses: marceloprado/has-changed-path@v1.0.1
        id: base-changed
        with:
          paths: ${{ format('.github/workflows/{0}', steps.setthis.outputs.naem) }} .github/workflows/framework.yml

      - name: run some stuff
        run: |
          echo "REACHED HERE"
        if: steps.base-changed.outputs.changed == 'true' && github.event_name == 'workflow_run'



    
    
